### ISSUE TITLE
Possibility to change table name in config

### ISSUE THREAD

**Issue by sarahyzova** [zerrium/zstats#5]
**Is your feature request related to a problem? Please describe.**
We have multiple servers connected via BungeeCord and we want to store stats from this servers in different tables.
Now we created multiple databases to separate the data but we have limited number of possible databases. It would be nice to be able to store data from all the servers in one database but separated for every server. 

**Describe the solution you'd like**
This problem can be solved by possibility to set database table name prefix or set table names at least. 

**Describe alternatives you've considered**
- using multiple databases (not effective)
- using different plugin (Hard to find better)

**Comment by zerrium** [comment]
@jakubhyza Hi, thank you for your suggestion, I will implement that on the next update in my free time
Also when 1.18 comes out, I will move my code base from Java 8 to Java 17, so be prepared 😉

Previously, I have done intensive Google searching to find if there is any plugin which can fulfill my need and I didn't find one, so that's why I decided to make this plugin 👍

**Comment by zerrium** [comment]
Hi @jakubhyza can you test if this plugin runs on your test server? I don't have access to my server PC right now. Delete config,yml and generate a new one by running the plugin and stop it. Make sure you are using JDK 17. Let me know if you find any issues/bugs 😊
[zstats_v3.0_Test.zip](https://github.com/zerrium/zstats/files/7559797/zstats_v3.0_Test.zip)

Edit: that jar is broken, use this one instead:
[zstats_v3.0_Test.zip](https://github.com/zerrium/zstats/files/7563385/zstats_v3.0_Test.zip)

**Comment by sarahyzova** [comment]
@zerrium
Sure. I'll do it right after I came home today.

**Comment by sarahyzova** [comment]
I told my friend to try it. (Because I don't have much free time)
He said he already write to you about it.
